/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import carteiraVacinacao.bean.Facade;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leona
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Facade fachada;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        TelaLoginModal tlm = new TelaLoginModal(this,true);
        tlm.setVisible(true);
        
        initComponents();
        
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        tela1 = new javax.swing.JPanel();
        painelCarteira = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVacina = new javax.swing.JTable();
        botaoRemoverVacinaCarteira = new javax.swing.JButton();
        botaoAlterarVacinaCarteira = new javax.swing.JButton();
        botaoInserirVacinaCarteira = new javax.swing.JButton();
        botaoAplicarVacinaCarteira = new javax.swing.JButton();
        painelBorda1 = new javax.swing.JPanel();
        cpfClienteCarteira = new javax.swing.JLabel();
        textCpfCarteira = new javax.swing.JTextField();
        textRacaCarteira = new javax.swing.JTextField();
        nomePetCarteira = new javax.swing.JLabel();
        botaoBuscarCarteira = new javax.swing.JButton();
        botaoLimparCarteira = new javax.swing.JButton();
        fundoCarteira = new javax.swing.JLabel();
        tela2 = new javax.swing.JPanel();
        painelModelo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableModelo1 = new javax.swing.JTable();
        botaoAlterarModelo = new javax.swing.JButton();
        botaoCadastrarModelo = new javax.swing.JButton();
        botaoExcluirModelo = new javax.swing.JButton();
        painelBorda2 = new javax.swing.JPanel();
        especiePetModelo = new javax.swing.JLabel();
        textEspecieModelo = new javax.swing.JTextField();
        racaPetModelo = new javax.swing.JLabel();
        textRacaModelo = new javax.swing.JTextField();
        botaoBuscarModelo = new javax.swing.JButton();
        botaoLimparModelo = new javax.swing.JButton();
        fundoModelo = new javax.swing.JLabel();
        tela3 = new javax.swing.JPanel();
        painelModelo1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableModelo2 = new javax.swing.JTable();
        botaoRemoverVacinaModelo = new javax.swing.JButton();
        botaoAlterarVacinaModelo = new javax.swing.JButton();
        botaoInserirVacinaModelo = new javax.swing.JButton();
        painelBorda3 = new javax.swing.JPanel();
        labelRaca = new javax.swing.JLabel();
        labelEspecie = new javax.swing.JLabel();
        fundoModelo1 = new javax.swing.JLabel();
        tela4 = new javax.swing.JPanel();
        painelModelo2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableModelo3 = new javax.swing.JTable();
        botaoRemoverVacinaModeloCadastrar = new javax.swing.JButton();
        botaoInserirVacinaModeloCadastrar = new javax.swing.JButton();
        painelBorda4 = new javax.swing.JPanel();
        especiePetModeloCadastrar = new javax.swing.JLabel();
        textEspecieModeloCadastrar = new javax.swing.JTextField();
        racaPetModeloCadastrar = new javax.swing.JLabel();
        textRacaModeloCadastrar = new javax.swing.JTextField();
        botaoCadastrarModeloCadastrar = new javax.swing.JButton();
        botaoLimparModeloCadastrar = new javax.swing.JButton();
        fundoModelo2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        carteiraVacinacao = new javax.swing.JMenu();
        modeloCarteira = new javax.swing.JMenu();
        imprimir = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Veterinária");
        setResizable(false);

        painelPrincipal.setLayout(new java.awt.CardLayout());

        tela1.setLayout(null);

        painelCarteira.setBackground(new java.awt.Color(255, 255, 255));
        painelCarteira.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableVacina.setBackground(new java.awt.Color(204, 204, 255));
        tableVacina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableVacina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeração", "Aplicação", "Data", "Nome da Vacina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVacina.setGridColor(new java.awt.Color(0, 0, 0));
        tableVacina.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tableVacina.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableVacina);
        if (tableVacina.getColumnModel().getColumnCount() > 0) {
            tableVacina.getColumnModel().getColumn(0).setMinWidth(100);
            tableVacina.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableVacina.getColumnModel().getColumn(0).setMaxWidth(100);
            tableVacina.getColumnModel().getColumn(1).setMinWidth(150);
            tableVacina.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableVacina.getColumnModel().getColumn(1).setMaxWidth(150);
            tableVacina.getColumnModel().getColumn(2).setMinWidth(200);
            tableVacina.getColumnModel().getColumn(2).setPreferredWidth(200);
            tableVacina.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        botaoRemoverVacinaCarteira.setText("Remover vacina");

        botaoAlterarVacinaCarteira.setText("Alterar vacina");

        botaoInserirVacinaCarteira.setText("Inserir vacina");

        botaoAplicarVacinaCarteira.setText("Aplicar vacina");

        painelBorda1.setBackground(new java.awt.Color(255, 255, 255));
        painelBorda1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Buscar carteira de vacinação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N

        cpfClienteCarteira.setText("CPF do Cliente:");

        nomePetCarteira.setText("Nome do Pet:");

        botaoBuscarCarteira.setText("Buscar");
        botaoBuscarCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBuscarCarteiraMouseClicked(evt);
            }
        });

        botaoLimparCarteira.setText("Limpar");
        botaoLimparCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparCarteiraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBorda1Layout = new javax.swing.GroupLayout(painelBorda1);
        painelBorda1.setLayout(painelBorda1Layout);
        painelBorda1Layout.setHorizontalGroup(
            painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBorda1Layout.createSequentialGroup()
                        .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCpfCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfClienteCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomePetCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textRacaCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBorda1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoLimparCarteira)
                        .addGap(54, 54, 54)
                        .addComponent(botaoBuscarCarteira)
                        .addGap(276, 276, 276))))
        );
        painelBorda1Layout.setVerticalGroup(
            painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfClienteCarteira)
                    .addComponent(nomePetCarteira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCpfCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRacaCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimparCarteira)
                    .addComponent(botaoBuscarCarteira))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelCarteiraLayout = new javax.swing.GroupLayout(painelCarteira);
        painelCarteira.setLayout(painelCarteiraLayout);
        painelCarteiraLayout.setHorizontalGroup(
            painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCarteiraLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(painelBorda1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelCarteiraLayout.createSequentialGroup()
                        .addGap(0, 330, Short.MAX_VALUE)
                        .addComponent(botaoAplicarVacinaCarteira)
                        .addGap(100, 100, 100)
                        .addComponent(botaoRemoverVacinaCarteira)
                        .addGap(100, 100, 100)
                        .addComponent(botaoAlterarVacinaCarteira)
                        .addGap(100, 100, 100)
                        .addComponent(botaoInserirVacinaCarteira)))
                .addGap(86, 86, 86))
        );
        painelCarteiraLayout.setVerticalGroup(
            painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCarteiraLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(painelBorda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserirVacinaCarteira)
                    .addComponent(botaoAlterarVacinaCarteira)
                    .addComponent(botaoRemoverVacinaCarteira)
                    .addComponent(botaoAplicarVacinaCarteira))
                .addGap(40, 40, 40))
        );

        tela1.add(painelCarteira);
        painelCarteira.setBounds(30, 30, 1260, 730);

        fundoCarteira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        tela1.add(fundoCarteira);
        fundoCarteira.setBounds(0, 0, 1330, 800);

        painelPrincipal.add(tela1, "tela1");

        tela2.setBackground(new java.awt.Color(0, 0, 153));
        tela2.setLayout(null);

        painelModelo.setBackground(new java.awt.Color(255, 255, 255));
        painelModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableModelo1.setBackground(new java.awt.Color(204, 204, 255));
        tableModelo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableModelo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeração", "Espécie", "Raça"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableModelo1.setGridColor(new java.awt.Color(0, 0, 0));
        tableModelo1.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tableModelo1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableModelo1);
        if (tableModelo1.getColumnModel().getColumnCount() > 0) {
            tableModelo1.getColumnModel().getColumn(0).setMinWidth(80);
            tableModelo1.getColumnModel().getColumn(0).setPreferredWidth(80);
            tableModelo1.getColumnModel().getColumn(0).setMaxWidth(80);
            tableModelo1.getColumnModel().getColumn(1).setMinWidth(400);
            tableModelo1.getColumnModel().getColumn(1).setPreferredWidth(400);
            tableModelo1.getColumnModel().getColumn(1).setMaxWidth(400);
        }

        botaoAlterarModelo.setText("Alterar modelo");
        botaoAlterarModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAlterarModeloMouseClicked(evt);
            }
        });

        botaoCadastrarModelo.setText("Cadastrar modelo");
        botaoCadastrarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarModeloActionPerformed(evt);
            }
        });

        botaoExcluirModelo.setText("Excluir modelo");
        botaoExcluirModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirModeloMouseClicked(evt);
            }
        });

        painelBorda2.setBackground(new java.awt.Color(255, 255, 255));
        painelBorda2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Busca por modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N

        especiePetModelo.setText("Espécie do Pet:");

        textEspecieModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEspecieModeloActionPerformed(evt);
            }
        });

        racaPetModelo.setText("Raça do Pet:");

        botaoBuscarModelo.setText("Buscar");
        botaoBuscarModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBuscarModeloMouseClicked(evt);
            }
        });

        botaoLimparModelo.setText("Limpar");
        botaoLimparModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparModeloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBorda2Layout = new javax.swing.GroupLayout(painelBorda2);
        painelBorda2.setLayout(painelBorda2Layout);
        painelBorda2Layout.setHorizontalGroup(
            painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBorda2Layout.createSequentialGroup()
                        .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especiePetModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEspecieModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(racaPetModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textRacaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelBorda2Layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addComponent(botaoLimparModelo)
                        .addGap(100, 100, 100)
                        .addComponent(botaoBuscarModelo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBorda2Layout.setVerticalGroup(
            painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda2Layout.createSequentialGroup()
                .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especiePetModelo)
                    .addComponent(racaPetModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEspecieModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRacaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelBorda2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimparModelo)
                    .addComponent(botaoBuscarModelo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelModeloLayout = new javax.swing.GroupLayout(painelModelo);
        painelModelo.setLayout(painelModeloLayout);
        painelModeloLayout.setHorizontalGroup(
            painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModeloLayout.createSequentialGroup()
                .addGroup(painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelModeloLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoExcluirModelo)
                        .addGap(100, 100, 100)
                        .addComponent(botaoAlterarModelo)
                        .addGap(100, 100, 100)
                        .addComponent(botaoCadastrarModelo))
                    .addGroup(painelModeloLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(painelBorda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE))))
                .addGap(86, 86, 86))
        );
        painelModeloLayout.setVerticalGroup(
            painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModeloLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(painelBorda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirModelo)
                    .addComponent(botaoAlterarModelo)
                    .addComponent(botaoCadastrarModelo))
                .addGap(40, 40, 40))
        );

        tela2.add(painelModelo);
        painelModelo.setBounds(30, 30, 1260, 730);

        fundoModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        fundoModelo.setText("jLabel1");
        tela2.add(fundoModelo);
        fundoModelo.setBounds(0, 0, 1330, 800);

        painelPrincipal.add(tela2, "tela2");

        tela3.setBackground(new java.awt.Color(0, 0, 153));
        tela3.setLayout(null);

        painelModelo1.setBackground(new java.awt.Color(255, 255, 255));
        painelModelo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableModelo2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableModelo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeração", "Nome da Vacina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableModelo2.setGridColor(new java.awt.Color(0, 0, 0));
        tableModelo2.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tableModelo2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tableModelo2);
        if (tableModelo2.getColumnModel().getColumnCount() > 0) {
            tableModelo2.getColumnModel().getColumn(0).setMinWidth(80);
            tableModelo2.getColumnModel().getColumn(0).setPreferredWidth(80);
            tableModelo2.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        botaoRemoverVacinaModelo.setText("Remover vacina");

        botaoAlterarVacinaModelo.setText("Alterar vacina");

        botaoInserirVacinaModelo.setText("Inserir vacina");

        painelBorda3.setBackground(new java.awt.Color(255, 255, 255));
        painelBorda3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        labelRaca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        labelEspecie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout painelBorda3Layout = new javax.swing.GroupLayout(painelBorda3);
        painelBorda3.setLayout(painelBorda3Layout);
        painelBorda3Layout.setHorizontalGroup(
            painelBorda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(labelRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBorda3Layout.setVerticalGroup(
            painelBorda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(painelBorda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelModelo1Layout = new javax.swing.GroupLayout(painelModelo1);
        painelModelo1.setLayout(painelModelo1Layout);
        painelModelo1Layout.setHorizontalGroup(
            painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModelo1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelBorda3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelModelo1Layout.createSequentialGroup()
                        .addGap(289, 553, Short.MAX_VALUE)
                        .addComponent(botaoRemoverVacinaModelo)
                        .addGap(100, 100, 100)
                        .addComponent(botaoAlterarVacinaModelo)
                        .addGap(100, 100, 100)
                        .addComponent(botaoInserirVacinaModelo)))
                .addGap(86, 86, 86))
        );
        painelModelo1Layout.setVerticalGroup(
            painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModelo1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(painelBorda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserirVacinaModelo)
                    .addComponent(botaoAlterarVacinaModelo)
                    .addComponent(botaoRemoverVacinaModelo))
                .addGap(58, 58, 58))
        );

        tela3.add(painelModelo1);
        painelModelo1.setBounds(30, 30, 1260, 730);

        fundoModelo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        fundoModelo1.setText("jLabel1");
        tela3.add(fundoModelo1);
        fundoModelo1.setBounds(0, 0, 1330, 800);

        painelPrincipal.add(tela3, "tela3");

        tela4.setBackground(new java.awt.Color(0, 0, 153));
        tela4.setLayout(null);

        painelModelo2.setBackground(new java.awt.Color(255, 255, 255));
        painelModelo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableModelo3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableModelo3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeração", "Nome da Vacina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableModelo3.setGridColor(new java.awt.Color(0, 0, 0));
        tableModelo3.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tableModelo3.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tableModelo3);
        if (tableModelo3.getColumnModel().getColumnCount() > 0) {
            tableModelo3.getColumnModel().getColumn(0).setMinWidth(80);
            tableModelo3.getColumnModel().getColumn(0).setPreferredWidth(80);
            tableModelo3.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        botaoRemoverVacinaModeloCadastrar.setText("Remover vacina");

        botaoInserirVacinaModeloCadastrar.setText("Inserir vacina");

        painelBorda4.setBackground(new java.awt.Color(255, 255, 255));
        painelBorda4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N

        especiePetModeloCadastrar.setText("Espécie do Pet:");

        textEspecieModeloCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEspecieModeloCadastrarActionPerformed(evt);
            }
        });

        racaPetModeloCadastrar.setText("Raça do Pet:");

        botaoCadastrarModeloCadastrar.setText("Cadastrar");
        botaoCadastrarModeloCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarModeloCadastrarMouseClicked(evt);
            }
        });

        botaoLimparModeloCadastrar.setText("Limpar");
        botaoLimparModeloCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparModeloCadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBorda4Layout = new javax.swing.GroupLayout(painelBorda4);
        painelBorda4.setLayout(painelBorda4Layout);
        painelBorda4Layout.setHorizontalGroup(
            painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBorda4Layout.createSequentialGroup()
                        .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especiePetModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEspecieModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(racaPetModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textRacaModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelBorda4Layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addComponent(botaoLimparModeloCadastrar)
                        .addGap(100, 100, 100)
                        .addComponent(botaoCadastrarModeloCadastrar)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        painelBorda4Layout.setVerticalGroup(
            painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda4Layout.createSequentialGroup()
                .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especiePetModeloCadastrar)
                    .addComponent(racaPetModeloCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEspecieModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRacaModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelBorda4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimparModeloCadastrar)
                    .addComponent(botaoCadastrarModeloCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelModelo2Layout = new javax.swing.GroupLayout(painelModelo2);
        painelModelo2.setLayout(painelModelo2Layout);
        painelModelo2Layout.setHorizontalGroup(
            painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModelo2Layout.createSequentialGroup()
                .addGroup(painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelModelo2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRemoverVacinaModeloCadastrar)
                        .addGap(100, 100, 100)
                        .addComponent(botaoInserirVacinaModeloCadastrar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelModelo2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelBorda4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))))
                .addGap(86, 86, 86))
        );
        painelModelo2Layout.setVerticalGroup(
            painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModelo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBorda4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserirVacinaModeloCadastrar)
                    .addComponent(botaoRemoverVacinaModeloCadastrar))
                .addGap(58, 58, 58))
        );

        tela4.add(painelModelo2);
        painelModelo2.setBounds(30, 30, 1260, 730);

        fundoModelo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        fundoModelo2.setText("jLabel1");
        tela4.add(fundoModelo2);
        fundoModelo2.setBounds(0, 0, 1330, 800);

        painelPrincipal.add(tela4, "tela4");

        carteiraVacinacao.setText("  Carteira de vacinação  ");
        carteiraVacinacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carteiraVacinacaoClicked(evt);
            }
        });
        jMenuBar1.add(carteiraVacinacao);

        modeloCarteira.setText("  Modelo de carteira  ");
        modeloCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeloCarteiraClicked(evt);
            }
        });
        jMenuBar1.add(modeloCarteira);

        imprimir.setText("  Imprimir  ");
        jMenuBar1.add(imprimir);

        sair.setText("  Sair  ");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carteiraVacinacaoClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteiraVacinacaoClicked
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "tela1");
        
        clearFields();
        clearTable();
        
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(false);
    }//GEN-LAST:event_carteiraVacinacaoClicked

    private void modeloCarteiraClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeloCarteiraClicked
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "tela2");
                
        clearFields();
        clearTable();
        
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(false);
    }//GEN-LAST:event_modeloCarteiraClicked

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // Deixa a tela principal invisivel
        this.setVisible(false);
        
        // Deixa a tela de login visivel 
        TelaLoginModal tlm = new TelaLoginModal(this,true);
        tlm.setVisible(true);
        
        // Depois de realizar o login, deixa a tela principal visivel novamente
        this.setVisible(true);
        
        // Carrega a primeira tela como inicio
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "tela1");
        
        // Limpa todas as tabelas
        clearTable();
        
        // Deixa todos os botoes inferiores invisiveis
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(false);
    }//GEN-LAST:event_sairMouseClicked

    @SuppressWarnings("empty-statement")
    private void botaoBuscarCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBuscarCarteiraMouseClicked
        // Limpa todas as tabelas
        clearTable();
        
        // DEixa os botoes inferiores invisiveis
        botaoInferiorCarteira(false);
     
        
      
        if(textCpfCarteira.getText().length() == 0){
            // CPF invalido
            JOptionPane.showMessageDialog(this,"Há campos vazios");
            return;
        }
        
        if(textCpfCarteira.getText().length() != 11){
            // CPF invalido
            JOptionPane.showMessageDialog(this,"CPF inválido");
            return;
        }
        else{
            String verificador = textCpfCarteira.getText();
           
            boolean valido = true;

            for (int i = 0; i < verificador.length(); i++) {
                Character caractere = verificador.charAt(i);
                if (!Character.isDigit(caractere)) {
                    //É String
                    valido = false;
                }
            }
            if(valido == false){
                JOptionPane.showMessageDialog(this,"CPF inválido");
                return;
            }
        }
       
        if(textRacaCarteira.getText().length() == 0){
            // Campo raca do pet vazio
            JOptionPane.showMessageDialog(this,"Há campos vazios");
            return;
        }
        
        if(textCpfCarteira.getText().equals("40510036805")){
            // Carteira encontrada
            String Demo = "NomeVacina;12/02/2018;T;Nome2;25/12/2018;F;";
            String Deli = ";";

            DefaultTableModel dtm = (DefaultTableModel) tableVacina.getModel();
            StringTokenizer Tok = new StringTokenizer(Demo);
            int n=1;
            String vacina,data,aplicada;

            while (Tok.hasMoreElements()){
                vacina = Tok.nextToken(Deli);
                data = Tok.nextToken(Deli);
                aplicada = Tok.nextToken(Deli);
                if(aplicada.equals("T")){
                    Object[] dados = {n,"Aplicada",data,vacina};
                    dtm.addRow(dados);
                }
                else{
                    Object[] dados = {n,"Nao aplicada",data,vacina};
                    dtm.addRow(dados);
                }
                n++;
            }
            clearFields();
            botaoInferiorCarteira(true);
        } 
        else {
            // Carteira nao encontrada
            int resposta = JOptionPane.showConfirmDialog(this,"Carteira desse pet não foi encontrada, deseja cadastrar uma nova carteira para esse pet?", "Carteira não encontrada!", JOptionPane.YES_NO_OPTION);
    
            if (resposta == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, "Cadastro");
            }
            clearFields();
        }
        
        
    }//GEN-LAST:event_botaoBuscarCarteiraMouseClicked

    private void botaoLimparCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparCarteiraMouseClicked
        // Limpa os campos
        clearFields();
    }//GEN-LAST:event_botaoLimparCarteiraMouseClicked

    private void botaoBuscarModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBuscarModeloMouseClicked
        // Deixa os botoes inferiores invisiveis
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(false);
        
        if(textEspecieModelo.getText().length() == 0){
            // Campo especie do pet vazio
            JOptionPane.showMessageDialog(this,"Preencha o campo Espécie do pet");
        }
        else{
            // Campo especie nao vazio
            if(textRacaModelo.getText().length() == 0){
                clearFields();
                // Campo raca do pet vazio
                
                int n = 1;
                String especie = textEspecieModelo.getText();
                String retorno =  fachada.buscarMod(textEspecieModelo.getText());
                
                if(retorno.length() == 0){
                    int resposta = JOptionPane.showConfirmDialog(this,"Modelo não foi encontrado, deseja cadastrar um novo modelo?", "Modelo não encontrado!", JOptionPane.YES_NO_OPTION);
    
                    if (resposta == JOptionPane.YES_OPTION) {
                        cadatrarModelo();
                    }
                    return;
                }
                
                String delimitador = ";";

                DefaultTableModel dtm = (DefaultTableModel) tableModelo1.getModel();
                StringTokenizer Tok = new StringTokenizer(retorno);
                String raca;
                
                while (Tok.hasMoreElements()){
                    raca = Tok.nextToken(delimitador);

                    Object[] dados = {n,especie,raca};
                    dtm.addRow(dados);
                   
                    n++;
                }

                botaoInferiorModeloInicial(true);
            }
            else{
                clearFields();
                // Campo raca do pet nao vazio
                // Busca por especie e raca e exibe tabela e botoes inferiores
                
                
                botaoInferiorModeloInicial(true);
                
                
            }
            
        }
        
    }//GEN-LAST:event_botaoBuscarModeloMouseClicked

    private void botaoLimparModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparModeloMouseClicked
        // Limpa os campos
        clearFields();
    }//GEN-LAST:event_botaoLimparModeloMouseClicked

    private void botaoCadastrarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarModeloActionPerformed

    private void botaoAlterarModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAlterarModeloMouseClicked
        int linha = tableModelo1.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione um modelo");
        }
        else{
            String Especie = (String) tableModelo1.getValueAt(linha,1);
            String Raca = (String) tableModelo1.getValueAt(linha,2);
            
            clearFields();
            clearTable();
            
            CardLayout cl = (CardLayout) painelPrincipal.getLayout();
            cl.show(painelPrincipal, "tela3");
        
            labelEspecie.setText("Espécie: " + Especie);
            labelRaca.setText("Raça: " + Raca);
            
            /* >>>>> Importante <<<<*/
            // realiza busca pela especie e raca e exibe tabela
            
            botaoInferiorModeloInicial(false);
            botaoInferiorModeloFinal(true);
        }
        
    }//GEN-LAST:event_botaoAlterarModeloMouseClicked

    private void botaoExcluirModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirModeloMouseClicked


        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirModeloMouseClicked

    private void textEspecieModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEspecieModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEspecieModeloActionPerformed

    private void textEspecieModeloCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEspecieModeloCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEspecieModeloCadastrarActionPerformed

    private void botaoCadastrarModeloCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarModeloCadastrarMouseClicked
        String e = textEspecieModeloCadastrar.getText();
        String r = textRacaModeloCadastrar.getText();
        int retorno = fachada.importarMod(e, r);
        if(retorno == 0){
            clearFields();
            JOptionPane.showMessageDialog(this,"Modelo foi cadastrado, insira vacinas");
            botaoInferiorCadastrarModelo(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"Modelo já cadastrado, altere espécie ou raça");
        }
    }//GEN-LAST:event_botaoCadastrarModeloCadastrarMouseClicked

    private void botaoLimparModeloCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparModeloCadastrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoLimparModeloCadastrarMouseClicked

    private void cadatrarModelo(){
        
        
    }
    
    private void clearFields(){
        // Primeira tela
        textCpfCarteira.setText("");
        textRacaCarteira.setText("");
        
        // Segunda tela
        textEspecieModelo.setText("");
        textRacaModelo.setText("");
        
        
    }
    
    private void clearTable(){
        DefaultTableModel dtm = (DefaultTableModel) tableVacina.getModel();
        while(dtm.getRowCount() != 0){
            dtm.removeRow(0);   
        }
        
        dtm = (DefaultTableModel) tableModelo1.getModel();
        while(dtm.getRowCount() != 0){
            dtm.removeRow(0);   
        }
        
        dtm = (DefaultTableModel) tableModelo2.getModel();
        while(dtm.getRowCount() != 0){
            dtm.removeRow(0);   
        }
    }
    
    private void botaoInferiorCarteira(boolean a){
        botaoRemoverVacinaCarteira.setVisible(a);
        botaoAlterarVacinaCarteira.setVisible(a);
        botaoAplicarVacinaCarteira.setVisible(a);
        botaoInserirVacinaCarteira.setVisible(a);
    }
    
    private void botaoInferiorModeloInicial(boolean a){
        botaoExcluirModelo.setVisible(a);
        botaoAlterarModelo.setVisible(a);
        botaoCadastrarModelo.setVisible(a);
    }
    
    private void botaoInferiorModeloFinal(boolean a){
        botaoRemoverVacinaModelo.setVisible(a);
        botaoAlterarVacinaModelo.setVisible(a);
        botaoInserirVacinaModelo.setVisible(a);
    }
        
    private void botaoInferiorCadastrarModelo(boolean a){
        botaoRemoverVacinaModeloCadastrar.setVisible(a);
        botaoInserirVacinaModeloCadastrar.setVisible(a);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAlterarModelo;
    private javax.swing.JButton botaoAlterarVacinaCarteira;
    private javax.swing.JButton botaoAlterarVacinaModelo;
    private javax.swing.JButton botaoAplicarVacinaCarteira;
    private javax.swing.JButton botaoBuscarCarteira;
    private javax.swing.JButton botaoBuscarModelo;
    private javax.swing.JButton botaoCadastrarModelo;
    private javax.swing.JButton botaoCadastrarModeloCadastrar;
    private javax.swing.JButton botaoExcluirModelo;
    private javax.swing.JButton botaoInserirVacinaCarteira;
    private javax.swing.JButton botaoInserirVacinaModelo;
    private javax.swing.JButton botaoInserirVacinaModeloCadastrar;
    private javax.swing.JButton botaoLimparCarteira;
    private javax.swing.JButton botaoLimparModelo;
    private javax.swing.JButton botaoLimparModeloCadastrar;
    private javax.swing.JButton botaoRemoverVacinaCarteira;
    private javax.swing.JButton botaoRemoverVacinaModelo;
    private javax.swing.JButton botaoRemoverVacinaModeloCadastrar;
    private javax.swing.JMenu carteiraVacinacao;
    private javax.swing.JLabel cpfClienteCarteira;
    private javax.swing.JLabel especiePetModelo;
    private javax.swing.JLabel especiePetModeloCadastrar;
    private javax.swing.JLabel fundoCarteira;
    private javax.swing.JLabel fundoModelo;
    private javax.swing.JLabel fundoModelo1;
    private javax.swing.JLabel fundoModelo2;
    private javax.swing.JMenu imprimir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelEspecie;
    private javax.swing.JLabel labelRaca;
    private javax.swing.JMenu modeloCarteira;
    private javax.swing.JLabel nomePetCarteira;
    private javax.swing.JPanel painelBorda1;
    private javax.swing.JPanel painelBorda2;
    private javax.swing.JPanel painelBorda3;
    private javax.swing.JPanel painelBorda4;
    private javax.swing.JPanel painelCarteira;
    private javax.swing.JPanel painelModelo;
    private javax.swing.JPanel painelModelo1;
    private javax.swing.JPanel painelModelo2;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JLabel racaPetModelo;
    private javax.swing.JLabel racaPetModeloCadastrar;
    private javax.swing.JMenu sair;
    private javax.swing.JTable tableModelo1;
    private javax.swing.JTable tableModelo2;
    private javax.swing.JTable tableModelo3;
    private javax.swing.JTable tableVacina;
    private javax.swing.JPanel tela1;
    private javax.swing.JPanel tela2;
    private javax.swing.JPanel tela3;
    private javax.swing.JPanel tela4;
    private javax.swing.JTextField textCpfCarteira;
    private javax.swing.JTextField textEspecieModelo;
    private javax.swing.JTextField textEspecieModeloCadastrar;
    private javax.swing.JTextField textRacaCarteira;
    private javax.swing.JTextField textRacaModelo;
    private javax.swing.JTextField textRacaModeloCadastrar;
    // End of variables declaration//GEN-END:variables
}
