/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import carteiraVacinacao.bean.Facade;
import com.itextpdf.text.DocumentException;
import java.awt.CardLayout;
import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leona
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private Facade fachada;
    private long id_cliente;
    private String nome_pet;
    
    public TelaPrincipal() {
        TelaLoginModal tlm = new TelaLoginModal(this,true);
        tlm.setVisible(true);
        
        fachada = new Facade();
        
        initComponents();
        
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(false);
        botaoInferiorCadastrarModelo(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        tela1 = new javax.swing.JPanel();
        painelCarteira = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVacina = new javax.swing.JTable();
        botaoRemoverVacinaCarteira = new javax.swing.JButton();
        botaoAgendarVacinaCarteira = new javax.swing.JButton();
        botaoInserirVacinaCarteira = new javax.swing.JButton();
        botaoAplicarVacinaCarteira = new javax.swing.JButton();
        painelBorda1 = new javax.swing.JPanel();
        cpfClienteCarteira = new javax.swing.JLabel();
        textCpfCarteira = new javax.swing.JTextField();
        nomePetCarteira = new javax.swing.JLabel();
        textNomeCarteira = new javax.swing.JTextField();
        botaoBuscarCarteira = new javax.swing.JButton();
        botaoLimparCarteira = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelCpf = new javax.swing.JLabel();
        labelC = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelN = new javax.swing.JLabel();
        fundoCarteira = new javax.swing.JLabel();
        tela2 = new javax.swing.JPanel();
        painelModelo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableModelo1 = new javax.swing.JTable();
        botaoAlterarModelo = new javax.swing.JButton();
        botaoCadastrarModelo = new javax.swing.JButton();
        botaoExcluirModelo = new javax.swing.JButton();
        painelBorda2 = new javax.swing.JPanel();
        especiePetModelo = new javax.swing.JLabel();
        textEspecieModelo = new javax.swing.JTextField();
        racaPetModelo = new javax.swing.JLabel();
        textRacaModelo = new javax.swing.JTextField();
        botaoBuscarModelo = new javax.swing.JButton();
        botaoLimparModelo = new javax.swing.JButton();
        fundoModelo = new javax.swing.JLabel();
        tela3 = new javax.swing.JPanel();
        painelModelo1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableModelo2 = new javax.swing.JTable();
        botaoRemoverVacinaModelo = new javax.swing.JButton();
        botaoInserirVacinaModelo = new javax.swing.JButton();
        painelBorda3 = new javax.swing.JPanel();
        labelRaca = new javax.swing.JLabel();
        labelEspecie = new javax.swing.JLabel();
        labelE = new javax.swing.JLabel();
        labelR = new javax.swing.JLabel();
        fundoModelo1 = new javax.swing.JLabel();
        tela4 = new javax.swing.JPanel();
        painelModelo2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableModelo3 = new javax.swing.JTable();
        botaoRemoverVacinaModeloCadastrar = new javax.swing.JButton();
        botaoInserirVacinaModeloCadastrar = new javax.swing.JButton();
        painelBorda4 = new javax.swing.JPanel();
        especiePetModeloCadastrar = new javax.swing.JLabel();
        textEspecieModeloCadastrar = new javax.swing.JTextField();
        racaPetModeloCadastrar = new javax.swing.JLabel();
        textRacaModeloCadastrar = new javax.swing.JTextField();
        botaoCadastrarModeloCadastrar = new javax.swing.JButton();
        fundoModelo2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        carteiraVacinacao = new javax.swing.JMenu();
        modeloCarteira = new javax.swing.JMenu();
        imprimir = new javax.swing.JMenu();
        sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clínica Veterinária");
        setResizable(false);

        painelPrincipal.setLayout(new java.awt.CardLayout());

        tela1.setLayout(null);

        painelCarteira.setBackground(new java.awt.Color(255, 255, 255));
        painelCarteira.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableVacina.setBackground(new java.awt.Color(153, 153, 255));
        tableVacina.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableVacina.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableVacina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeração", "Aplicação", "Data", "Nome da Vacina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVacina.setGridColor(new java.awt.Color(0, 0, 0));
        tableVacina.setRowHeight(30);
        tableVacina.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tableVacina.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableVacina);
        if (tableVacina.getColumnModel().getColumnCount() > 0) {
            tableVacina.getColumnModel().getColumn(0).setMinWidth(100);
            tableVacina.getColumnModel().getColumn(0).setPreferredWidth(100);
            tableVacina.getColumnModel().getColumn(0).setMaxWidth(100);
            tableVacina.getColumnModel().getColumn(1).setMinWidth(150);
            tableVacina.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableVacina.getColumnModel().getColumn(1).setMaxWidth(150);
            tableVacina.getColumnModel().getColumn(2).setMinWidth(200);
            tableVacina.getColumnModel().getColumn(2).setPreferredWidth(200);
            tableVacina.getColumnModel().getColumn(2).setMaxWidth(200);
        }

        botaoRemoverVacinaCarteira.setText("Remover vacina");
        botaoRemoverVacinaCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoRemoverVacinaCarteiraMouseClicked(evt);
            }
        });

        botaoAgendarVacinaCarteira.setText("Agendar vacina");
        botaoAgendarVacinaCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAgendarVacinaCarteiraMouseClicked(evt);
            }
        });

        botaoInserirVacinaCarteira.setText("Inserir vacina");
        botaoInserirVacinaCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoInserirVacinaCarteiraMouseClicked(evt);
            }
        });

        botaoAplicarVacinaCarteira.setText("Aplicar vacina");
        botaoAplicarVacinaCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAplicarVacinaCarteiraMouseClicked(evt);
            }
        });

        painelBorda1.setBackground(new java.awt.Color(255, 255, 255));
        painelBorda1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Buscar carteira de vacinação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N

        cpfClienteCarteira.setText("CPF do Cliente:");

        nomePetCarteira.setText("Nome do Pet:");

        botaoBuscarCarteira.setText("Buscar");
        botaoBuscarCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBuscarCarteiraMouseClicked(evt);
            }
        });

        botaoLimparCarteira.setText("Limpar");
        botaoLimparCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparCarteiraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBorda1Layout = new javax.swing.GroupLayout(painelBorda1);
        painelBorda1.setLayout(painelBorda1Layout);
        painelBorda1Layout.setHorizontalGroup(
            painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCpfCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfClienteCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNomeCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomePetCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelBorda1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(botaoLimparCarteira)
                        .addGap(100, 100, 100)
                        .addComponent(botaoBuscarCarteira)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        painelBorda1Layout.setVerticalGroup(
            painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfClienteCarteira)
                    .addComponent(nomePetCarteira))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textCpfCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNomeCarteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(painelBorda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimparCarteira)
                    .addComponent(botaoBuscarCarteira))
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Dados da carteira de vacinação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N

        labelCpf.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelCpf.setText("CPF do cliente:");

        labelC.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        labelNome.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        labelNome.setText("Nome do Pet:");

        labelN.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelC, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCpf))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNome)
                    .addComponent(labelN, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCpf)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelCarteiraLayout = new javax.swing.GroupLayout(painelCarteira);
        painelCarteira.setLayout(painelCarteiraLayout);
        painelCarteiraLayout.setHorizontalGroup(
            painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCarteiraLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(painelBorda1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelCarteiraLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoInserirVacinaCarteira)
                        .addGap(100, 100, 100)
                        .addComponent(botaoRemoverVacinaCarteira)
                        .addGap(100, 100, 100)
                        .addComponent(botaoAgendarVacinaCarteira)
                        .addGap(100, 100, 100)
                        .addComponent(botaoAplicarVacinaCarteira)))
                .addGap(86, 86, 86))
        );
        painelCarteiraLayout.setVerticalGroup(
            painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCarteiraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBorda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(painelCarteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserirVacinaCarteira)
                    .addComponent(botaoRemoverVacinaCarteira)
                    .addComponent(botaoAplicarVacinaCarteira)
                    .addComponent(botaoAgendarVacinaCarteira))
                .addGap(40, 40, 40))
        );

        tela1.add(painelCarteira);
        painelCarteira.setBounds(30, 30, 1260, 730);

        fundoCarteira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        tela1.add(fundoCarteira);
        fundoCarteira.setBounds(0, 0, 1330, 800);

        painelPrincipal.add(tela1, "tela1");

        tela2.setBackground(new java.awt.Color(0, 0, 153));
        tela2.setLayout(null);

        painelModelo.setBackground(new java.awt.Color(255, 255, 255));
        painelModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableModelo1.setBackground(new java.awt.Color(153, 153, 255));
        tableModelo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableModelo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableModelo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeração", "Espécie", "Raça"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableModelo1.setGridColor(new java.awt.Color(0, 0, 0));
        tableModelo1.setRowHeight(30);
        tableModelo1.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tableModelo1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableModelo1);
        if (tableModelo1.getColumnModel().getColumnCount() > 0) {
            tableModelo1.getColumnModel().getColumn(0).setMinWidth(80);
            tableModelo1.getColumnModel().getColumn(0).setPreferredWidth(80);
            tableModelo1.getColumnModel().getColumn(0).setMaxWidth(80);
            tableModelo1.getColumnModel().getColumn(1).setMinWidth(400);
            tableModelo1.getColumnModel().getColumn(1).setPreferredWidth(400);
            tableModelo1.getColumnModel().getColumn(1).setMaxWidth(400);
        }

        botaoAlterarModelo.setText("Alterar modelo");
        botaoAlterarModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAlterarModeloMouseClicked(evt);
            }
        });

        botaoCadastrarModelo.setText("Cadastrar modelo");
        botaoCadastrarModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarModeloMouseClicked(evt);
            }
        });

        botaoExcluirModelo.setText("Excluir modelo");
        botaoExcluirModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoExcluirModeloMouseClicked(evt);
            }
        });

        painelBorda2.setBackground(new java.awt.Color(255, 255, 255));
        painelBorda2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Busca por modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N

        especiePetModelo.setText("Espécie do Pet:");

        racaPetModelo.setText("Raça do Pet:");

        botaoBuscarModelo.setText("Buscar");
        botaoBuscarModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBuscarModeloMouseClicked(evt);
            }
        });

        botaoLimparModelo.setText("Limpar");
        botaoLimparModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoLimparModeloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelBorda2Layout = new javax.swing.GroupLayout(painelBorda2);
        painelBorda2.setLayout(painelBorda2Layout);
        painelBorda2Layout.setHorizontalGroup(
            painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelBorda2Layout.createSequentialGroup()
                        .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(especiePetModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEspecieModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110)
                        .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(racaPetModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textRacaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelBorda2Layout.createSequentialGroup()
                        .addGap(547, 547, 547)
                        .addComponent(botaoLimparModelo)
                        .addGap(100, 100, 100)
                        .addComponent(botaoBuscarModelo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBorda2Layout.setVerticalGroup(
            painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda2Layout.createSequentialGroup()
                .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especiePetModelo)
                    .addComponent(racaPetModelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEspecieModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRacaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelBorda2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(painelBorda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoLimparModelo)
                    .addComponent(botaoBuscarModelo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelModeloLayout = new javax.swing.GroupLayout(painelModelo);
        painelModelo.setLayout(painelModeloLayout);
        painelModeloLayout.setHorizontalGroup(
            painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModeloLayout.createSequentialGroup()
                .addGroup(painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelModeloLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoExcluirModelo)
                        .addGap(150, 150, 150)
                        .addComponent(botaoAlterarModelo)
                        .addGap(150, 150, 150)
                        .addComponent(botaoCadastrarModelo))
                    .addGroup(painelModeloLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(painelBorda2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE))))
                .addGap(86, 86, 86))
        );
        painelModeloLayout.setVerticalGroup(
            painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModeloLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(painelBorda2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(painelModeloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirModelo)
                    .addComponent(botaoAlterarModelo)
                    .addComponent(botaoCadastrarModelo))
                .addGap(40, 40, 40))
        );

        tela2.add(painelModelo);
        painelModelo.setBounds(30, 30, 1260, 730);

        fundoModelo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        fundoModelo.setText("jLabel1");
        tela2.add(fundoModelo);
        fundoModelo.setBounds(0, 0, 1330, 800);

        painelPrincipal.add(tela2, "tela2");

        tela3.setBackground(new java.awt.Color(0, 0, 153));
        tela3.setLayout(null);

        painelModelo1.setBackground(new java.awt.Color(255, 255, 255));
        painelModelo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableModelo2.setBackground(new java.awt.Color(153, 153, 255));
        tableModelo2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableModelo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableModelo2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeração", "Nome da Vacina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableModelo2.setGridColor(new java.awt.Color(0, 0, 0));
        tableModelo2.setRowHeight(30);
        tableModelo2.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tableModelo2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tableModelo2);
        if (tableModelo2.getColumnModel().getColumnCount() > 0) {
            tableModelo2.getColumnModel().getColumn(0).setMinWidth(80);
            tableModelo2.getColumnModel().getColumn(0).setPreferredWidth(80);
            tableModelo2.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        botaoRemoverVacinaModelo.setText("Remover vacina");
        botaoRemoverVacinaModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoRemoverVacinaModeloMouseClicked(evt);
            }
        });

        botaoInserirVacinaModelo.setText("Inserir vacina");
        botaoInserirVacinaModelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoInserirVacinaModeloMouseClicked(evt);
            }
        });

        painelBorda3.setBackground(new java.awt.Color(255, 255, 255));
        painelBorda3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        labelRaca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        labelEspecie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        labelE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelE.setText("Espécie:");

        labelR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelR.setText("Raça:");

        javax.swing.GroupLayout painelBorda3Layout = new javax.swing.GroupLayout(painelBorda3);
        painelBorda3.setLayout(painelBorda3Layout);
        painelBorda3Layout.setHorizontalGroup(
            painelBorda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelE)
                .addGap(18, 18, 18)
                .addComponent(labelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(labelR)
                .addGap(18, 18, 18)
                .addComponent(labelRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );
        painelBorda3Layout.setVerticalGroup(
            painelBorda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBorda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelE, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelModelo1Layout = new javax.swing.GroupLayout(painelModelo1);
        painelModelo1.setLayout(painelModelo1Layout);
        painelModelo1Layout.setHorizontalGroup(
            painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModelo1Layout.createSequentialGroup()
                .addGroup(painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelModelo1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoRemoverVacinaModelo)
                        .addGap(150, 150, 150)
                        .addComponent(botaoInserirVacinaModelo))
                    .addGroup(painelModelo1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(painelBorda3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(86, 86, 86))
        );
        painelModelo1Layout.setVerticalGroup(
            painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModelo1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(painelBorda3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(painelModelo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRemoverVacinaModelo)
                    .addComponent(botaoInserirVacinaModelo))
                .addGap(40, 40, 40))
        );

        tela3.add(painelModelo1);
        painelModelo1.setBounds(30, 30, 1260, 730);

        fundoModelo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        fundoModelo1.setText("jLabel1");
        tela3.add(fundoModelo1);
        fundoModelo1.setBounds(0, 0, 1330, 800);

        painelPrincipal.add(tela3, "tela3");

        tela4.setBackground(new java.awt.Color(0, 0, 153));
        tela4.setLayout(null);

        painelModelo2.setBackground(new java.awt.Color(255, 255, 255));
        painelModelo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableModelo3.setBackground(new java.awt.Color(153, 153, 255));
        tableModelo3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tableModelo3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tableModelo3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numeração", "Nome da Vacina"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableModelo3.setGridColor(new java.awt.Color(0, 0, 0));
        tableModelo3.setRowHeight(30);
        tableModelo3.setSelectionBackground(new java.awt.Color(0, 0, 153));
        tableModelo3.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tableModelo3);
        if (tableModelo3.getColumnModel().getColumnCount() > 0) {
            tableModelo3.getColumnModel().getColumn(0).setMinWidth(80);
            tableModelo3.getColumnModel().getColumn(0).setPreferredWidth(80);
            tableModelo3.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        botaoRemoverVacinaModeloCadastrar.setText("Remover vacina");
        botaoRemoverVacinaModeloCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoRemoverVacinaModeloCadastrarMouseClicked(evt);
            }
        });

        botaoInserirVacinaModeloCadastrar.setText("Inserir vacina");
        botaoInserirVacinaModeloCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoInserirVacinaModeloCadastrarMouseClicked(evt);
            }
        });

        painelBorda4.setBackground(new java.awt.Color(255, 255, 255));
        painelBorda4.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)))); // NOI18N

        especiePetModeloCadastrar.setText("Espécie do Pet:");

        racaPetModeloCadastrar.setText("Raça do Pet:");

        javax.swing.GroupLayout painelBorda4Layout = new javax.swing.GroupLayout(painelBorda4);
        painelBorda4.setLayout(painelBorda4Layout);
        painelBorda4Layout.setHorizontalGroup(
            painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(especiePetModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEspecieModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110)
                .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(racaPetModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRacaModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBorda4Layout.setVerticalGroup(
            painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBorda4Layout.createSequentialGroup()
                .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especiePetModeloCadastrar)
                    .addComponent(racaPetModeloCadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBorda4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEspecieModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRacaModeloCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        botaoCadastrarModeloCadastrar.setText("Cadastrar");
        botaoCadastrarModeloCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarModeloCadastrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout painelModelo2Layout = new javax.swing.GroupLayout(painelModelo2);
        painelModelo2.setLayout(painelModelo2Layout);
        painelModelo2Layout.setHorizontalGroup(
            painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModelo2Layout.createSequentialGroup()
                .addGroup(painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelModelo2Layout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addComponent(botaoInserirVacinaModeloCadastrar)
                        .addGap(150, 150, 150)
                        .addComponent(botaoRemoverVacinaModeloCadastrar)
                        .addGap(150, 150, 150)
                        .addComponent(botaoCadastrarModeloCadastrar))
                    .addGroup(painelModelo2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelBorda4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane5))))
                .addGap(86, 86, 86))
        );
        painelModelo2Layout.setVerticalGroup(
            painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelModelo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelBorda4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(painelModelo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoInserirVacinaModeloCadastrar)
                    .addComponent(botaoCadastrarModeloCadastrar)
                    .addComponent(botaoRemoverVacinaModeloCadastrar))
                .addGap(40, 40, 40))
        );

        tela4.add(painelModelo2);
        painelModelo2.setBounds(30, 30, 1260, 730);

        fundoModelo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fundo.jpg"))); // NOI18N
        fundoModelo2.setText("jLabel1");
        tela4.add(fundoModelo2);
        fundoModelo2.setBounds(0, 0, 1330, 800);

        painelPrincipal.add(tela4, "tela4");

        carteiraVacinacao.setText("  Carteira de vacinação  ");
        carteiraVacinacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carteiraVacinacaoClicked(evt);
            }
        });
        jMenuBar1.add(carteiraVacinacao);

        modeloCarteira.setText("  Modelo de carteira  ");
        modeloCarteira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modeloCarteiraClicked(evt);
            }
        });
        jMenuBar1.add(modeloCarteira);

        imprimir.setText("  Gerar carteira  ");
        imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprimirMouseClicked(evt);
            }
        });
        jMenuBar1.add(imprimir);

        sair.setText("  Sair  ");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1329, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 797, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carteiraVacinacaoClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carteiraVacinacaoClicked
        mudarToTela1();
    }//GEN-LAST:event_carteiraVacinacaoClicked

    private void modeloCarteiraClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modeloCarteiraClicked
        mudarToTela2();
    }//GEN-LAST:event_modeloCarteiraClicked

    private void sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMouseClicked
        // Deixa a tela principal invisivel
        this.setVisible(false);
        
        // Deixa a tela de login visivel 
        TelaLoginModal tlm = new TelaLoginModal(this,true);
        tlm.setVisible(true);
        
        // Depois de realizar o login, deixa a tela principal visivel novamente
        this.setVisible(true);
        
        // Carrega a primeira tela como inicio
        mudarToTela1();
    }//GEN-LAST:event_sairMouseClicked

    //@SuppressWarnings("empty-statement")
    private void botaoBuscarCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBuscarCarteiraMouseClicked
        // Limpa todas as tabelas
        clearTable();
        
        // DEixa os botoes inferiores invisiveis
        botaoInferiorCarteira(false);

        if(textCpfCarteira.getText().length() == 0){
            // CPF invalido
            JOptionPane.showMessageDialog(this,"Há campos vazios");
            return;
        }
        
        if(textNomeCarteira.getText().length() == 0){
            // Campo raca do pet vazio
            JOptionPane.showMessageDialog(this,"Há campos vazios");
            return;
        }
        
        if(textCpfCarteira.getText().length() != 11){
            // CPF invalido
            JOptionPane.showMessageDialog(this,"CPF inválido");
            return;
        }
        else{
            String verificador = textCpfCarteira.getText();
           
            boolean valido = true;

            for (int i = 0; i < verificador.length(); i++) {
                Character caractere = verificador.charAt(i);
                if (!Character.isDigit(caractere)) {
                    //É letra
                    valido = false;
                }
            }
            if(valido == false){
                JOptionPane.showMessageDialog(this,"CPF inválido");
                return;
            }
        }
        String c = textCpfCarteira.getText();
        long cpf = Long.parseLong(textCpfCarteira.getText());
        String nome = textNomeCarteira.getText();
        id_cliente = cpf;
        nome_pet = nome;
        boolean retorno = fachada.buscarCart(cpf,nome);
                
        
        if(retorno == true){
            // Carteira encontrada
            String Demo = fachada.getVetorVacina();
            String Deli = ";";
            if(Demo.equals("")){
                clearFields();
                botaoInferiorCarteira(true);
                labelC.setText(c);
                labelN.setText(nome);
                return;
            }
            DefaultTableModel dtm = (DefaultTableModel) tableVacina.getModel();
            StringTokenizer Tok = new StringTokenizer(Demo);
            int n=1;
            String vacina,data,aplicada;

            while (Tok.hasMoreElements()){
                vacina = Tok.nextToken(Deli);
                data = Tok.nextToken(Deli);
                aplicada = Tok.nextToken(Deli);
                if(aplicada.equals("T")){
                    Object[] dados = {n,"Aplicada",data,vacina};
                    dtm.addRow(dados);
                }
                else{
                    Object[] dados = {n,"Não aplicada",data,vacina};
                    dtm.addRow(dados);
                }
                n++;
            }
            clearFields();
            botaoInferiorCarteira(true);
            labelC.setText(c);
            labelN.setText(nome);
        } 
        else {
            // Carteira nao encontrada
            int resposta = JOptionPane.showConfirmDialog(this,"Carteira desse pet não foi encontrada, deseja cadastrar uma nova carteira com esses dados?", "Carteira não encontrada!", JOptionPane.YES_NO_OPTION);
    
            if (resposta == JOptionPane.YES_OPTION){
                fachada.cadastrarCart(cpf,nome);
                labelC.setText(c);
                labelN.setText(nome);
                boolean r = fachada.verificaModelo(cpf,nome);
                if(r == true){
                    int importar = JOptionPane.showConfirmDialog(this,"Carteira desse pet foi cadastrada com sucesso, deseja importar um modelo pré definido?", "Carteira cadastrada!", JOptionPane.YES_NO_OPTION);
                    if(importar == JOptionPane.YES_OPTION){
                        fachada.importarModelo(cpf,nome);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Carteira desse pet foi cadastrada com sucesso");
                }
                
            }
            clearFields();
        }
        
        
    }//GEN-LAST:event_botaoBuscarCarteiraMouseClicked

    private void botaoLimparCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparCarteiraMouseClicked
        String c = labelC.getText();
        String n = labelN.getText();
        
        // Limpa os campos
        clearFields();
        
        labelC.setText(c);
        labelN.setText(n);
    }//GEN-LAST:event_botaoLimparCarteiraMouseClicked

    private void botaoBuscarModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBuscarModeloMouseClicked

        if(textEspecieModelo.getText().length() == 0){
            // Campo especie do pet vazio
            JOptionPane.showMessageDialog(this,"Preencha o campo Espécie do pet");
        }
        else{
            
            // Campo especie nao vazio
            if(textRacaModelo.getText().length() == 0){
                
                // Campo raca do pet vazio
                clearTable();
                int n = 1;
                String especie = textEspecieModelo.getText();
                
                String retorno =  fachada.buscarMod(especie);
                
                if(retorno.length() == 0){
                    int resposta = JOptionPane.showConfirmDialog(this,"Modelo não foi encontrado, deseja cadastrar um novo modelo?", "Modelo não encontrado!", JOptionPane.YES_NO_OPTION);
    
                    if (resposta == JOptionPane.YES_OPTION) {  
                        mudarToTela4();
                    }
                    return;
                }
                
                String delimitador = ";";

                DefaultTableModel dtm = (DefaultTableModel) tableModelo1.getModel();
                StringTokenizer Tok = new StringTokenizer(retorno);
                String r,e;
                
                while (Tok.hasMoreElements()){
                    e = Tok.nextToken(delimitador);
                    r = Tok.nextToken(delimitador);
                   
                    Object[] dados = {n,e,r};
                    dtm.addRow(dados);
                   
                    n++;
                }

                botaoInferiorModeloInicial(true);
                clearFields();
            }
            else{ 
                // Campo raca do pet nao vazio
                clearTable();
                String e = textEspecieModelo.getText();
                String r = textRacaModelo.getText();
                
                if(!fachada.importarMod(e, r)){
                    int resposta = JOptionPane.showConfirmDialog(this,"Modelo não foi encontrado, deseja cadastrar um novo modelo?", "Modelo não encontrado!", JOptionPane.YES_NO_OPTION);
    
                    if (resposta == JOptionPane.YES_OPTION) {  
                        
                        mudarToTela4();
                    }
                    return;
                }

                DefaultTableModel dtm = (DefaultTableModel) tableModelo1.getModel();
                Object[] dados = {1,e,r};
                dtm.addRow(dados);

                clearFields();
                botaoInferiorModeloInicial(true);
                
                
            }
            
        }
        
    }//GEN-LAST:event_botaoBuscarModeloMouseClicked

    private void botaoLimparModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoLimparModeloMouseClicked
        // Limpa os campos
        clearFields();
    }//GEN-LAST:event_botaoLimparModeloMouseClicked

    private void botaoAlterarModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAlterarModeloMouseClicked
        int linha = tableModelo1.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione um modelo");
        }
        else{
            String Especie = (String) tableModelo1.getValueAt(linha,1);
            String Raca = (String) tableModelo1.getValueAt(linha,2);
            
            mudarToTela3();
        
            labelEspecie.setText(Especie);
            labelRaca.setText(Raca);
            
            /* >>>>> Importante <<<<*/
            // realiza busca pela especie e raca e exibe tabela
            String retorno = fachada.getVetorVacina(Especie, Raca);
            if(!retorno.equals("")){
                DefaultTableModel dtm = (DefaultTableModel) tableModelo2.getModel();
                StringTokenizer Tok = new StringTokenizer(retorno);
                String v,delimitador = ";";
                int n=1;
                while (Tok.hasMoreElements()){
                    v = Tok.nextToken(delimitador);
                   
                    Object[] dados = {n,v};
                    dtm.addRow(dados);
                   
                    n++;
                }
            }
            
            
        }
        
    }//GEN-LAST:event_botaoAlterarModeloMouseClicked

    private void botaoExcluirModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExcluirModeloMouseClicked
        int linha = tableModelo1.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione um modelo");
        }
        else{
            String Especie = (String) tableModelo1.getValueAt(linha,1);
            String Raca = (String) tableModelo1.getValueAt(linha,2);
            
            if(fachada.excluirMod(Especie, Raca)){
                DefaultTableModel dtm = (DefaultTableModel) tableModelo1.getModel();
                dtm.removeRow(linha);  
                JOptionPane.showMessageDialog(this,"Modelo excluido com sucesso!");
            }
            

        }
    }//GEN-LAST:event_botaoExcluirModeloMouseClicked

    private void botaoCadastrarModeloCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarModeloCadastrarMouseClicked
        String e = textEspecieModeloCadastrar.getText();
        String r = textRacaModeloCadastrar.getText();
        
        
        if(!fachada.importarMod(e, r)){
            clearFields();
            DefaultTableModel dtm = (DefaultTableModel) tableModelo3.getModel();
            fachada.cadastrarMod(e, r);
            int i = 0;
            while(i < dtm.getRowCount()){
                String vacina = (String) tableModelo3.getValueAt(i,1);
                
                fachada.addVacina(e,r,vacina);
                i++;
            }
            
            JOptionPane.showMessageDialog(this,"Modelo cadastrado com sucesso");
            
            mudarToTela2();
        }
        else{
            JOptionPane.showMessageDialog(this,"Modelo já cadastrado, altere espécie ou raça");
        }
    }//GEN-LAST:event_botaoCadastrarModeloCadastrarMouseClicked

    private void botaoInserirVacinaModeloCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoInserirVacinaModeloCadastrarMouseClicked
        InserirVacina inserir = new InserirVacina(this,true);
        inserir.setVisible(true);
        String retorno = inserir.getVacina();
        
        
        
        if(!retorno.equals("")){
            
            DefaultTableModel dtm = (DefaultTableModel) tableModelo3.getModel();
            int n = dtm.getRowCount();
            Object[] dados = {n+1,retorno};
            dtm.addRow(dados);
            JOptionPane.showMessageDialog(this,"Vacina inserida com sucesso!");
           
            
        }
    }//GEN-LAST:event_botaoInserirVacinaModeloCadastrarMouseClicked

    private void imprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirMouseClicked
        /// nao implementado ainda
        ///fachada.imprimir(e,r);
    }//GEN-LAST:event_imprimirMouseClicked

    private void botaoCadastrarModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarModeloMouseClicked
        mudarToTela4();
    }//GEN-LAST:event_botaoCadastrarModeloMouseClicked

    private void botaoInserirVacinaCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoInserirVacinaCarteiraMouseClicked
        InserirVacina inserir = new InserirVacina(this,true);
        inserir.setVisible(true);
        String retorno = inserir.getVacina();
        String c = labelC.getText();
        long cpf = Long.parseLong(c);
        String nome = labelN.getText();
        
        if(!retorno.equals("")){
            if(fachada.addVacina(cpf,nome,retorno)){
                DefaultTableModel dtm = (DefaultTableModel) tableVacina.getModel();
                int n = dtm.getRowCount();
                Object[] dados = {n+1,"Não aplicada"," ",retorno};
                dtm.addRow(dados);
                JOptionPane.showMessageDialog(this,"Vacina inserida com sucesso!");
            }
            else{
                JOptionPane.showMessageDialog(this,"Não foi possível inserir essa vacina!");
            }
        }
    }//GEN-LAST:event_botaoInserirVacinaCarteiraMouseClicked
    
        
    private void botaoRemoverVacinaCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverVacinaCarteiraMouseClicked
        int linha = tableVacina.getSelectedRow();
        String c = labelC.getText();
        long cpf = Long.parseLong(c);
        String nome = labelN.getText();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione uma vacina");
        }
        else{
            String nomeVacina = (String) tableVacina.getValueAt(linha,3);
            if(fachada.delVacina(cpf,nome,nomeVacina)){
                int n = linha;
                DefaultTableModel dtm = (DefaultTableModel) tableVacina.getModel();
                dtm.removeRow(linha);   
                
                while(n < dtm.getRowCount()){
                    dtm.setValueAt(n+1, n, 0);
                    n++;
                }
                JOptionPane.showMessageDialog(this,"Vacina removida com sucesso!");
            }
            else{
                JOptionPane.showMessageDialog(this,"Não foi possível remover essa vacina!");
            }
            
        }
    }//GEN-LAST:event_botaoRemoverVacinaCarteiraMouseClicked

    private void botaoAgendarVacinaCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAgendarVacinaCarteiraMouseClicked
        int linha = tableVacina.getSelectedRow();
        String c = labelC.getText();
        long cpf = Long.parseLong(c);
        String nome = labelN.getText();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione uma vacina");
        }
        else{
            AplicarVacina aplicar = new AplicarVacina(this,true);
            aplicar.setVisible(true);
            String retorno = aplicar.getVacina();
            if(!retorno.equals("")){

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    Date dataAux;
                    dataAux = sdf.parse(retorno);
                    fachada.agendarVacina(cpf,nome,tableVacina.getValueAt(linha, 3).toString(), dataAux);
                    tableVacina.setValueAt(retorno, linha, 2);
                } catch(Exception e){
                    JOptionPane.showMessageDialog(this,"Data invalida!");
                }
                
            }
    
        }


    }//GEN-LAST:event_botaoAgendarVacinaCarteiraMouseClicked

    private void botaoInserirVacinaModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoInserirVacinaModeloMouseClicked
        InserirVacina inserir = new InserirVacina(this,true);
        inserir.setVisible(true);
        String retorno = inserir.getVacina();
        String e = labelEspecie.getText();
        String r = labelRaca.getText();
        
        if(!retorno.equals("")){
            if(fachada.addVacina(e,r,retorno)){
                DefaultTableModel dtm = (DefaultTableModel) tableModelo2.getModel();
                int n = dtm.getRowCount();
                Object[] dados = {n+1,retorno};
                dtm.addRow(dados);
                JOptionPane.showMessageDialog(this,"Vacina inserida com sucesso!");
            }
            else{
                JOptionPane.showMessageDialog(this,"Não foi possível inserir essa vacina!");
            }
        }



    }//GEN-LAST:event_botaoInserirVacinaModeloMouseClicked

    private void botaoRemoverVacinaModeloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverVacinaModeloMouseClicked
        int linha = tableModelo2.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione uma vacina");
        }
        else{
            String nomeVacina = (String) tableModelo2.getValueAt(linha,1);
            String e = labelEspecie.getText();
            String r = labelRaca.getText();
            
            if(fachada.delVacina(e,r,nomeVacina)){
                int n = linha;
                DefaultTableModel dtm = (DefaultTableModel) tableModelo2.getModel();
                dtm.removeRow(linha);   
                
                while(n < dtm.getRowCount()){
                    dtm.setValueAt(n+1, n, 0);
                    n++;
                }
                JOptionPane.showMessageDialog(this,"Vacina removida com sucesso!");
            }
            else{
                JOptionPane.showMessageDialog(this,"Não foi possível remover essa vacina!");
            }
            
        }
    }//GEN-LAST:event_botaoRemoverVacinaModeloMouseClicked

    private void botaoAplicarVacinaCarteiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAplicarVacinaCarteiraMouseClicked
        int linha = tableVacina.getSelectedRow();
        String c = labelC.getText();
        long cpf = Long.parseLong(c);
        String nome = labelN.getText();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione uma vacina");
        }
        else{
            String nomeVacina = (String) tableVacina.getValueAt(linha,3);
            if(fachada.aplicarVacina(cpf, nome, nomeVacina)){
                tableVacina.setValueAt("Aplicada", linha, 1);
                JOptionPane.showMessageDialog(this,"Vacina aplicada com sucesso");
                
            }
        }

    }//GEN-LAST:event_botaoAplicarVacinaCarteiraMouseClicked

    private void botaoRemoverVacinaModeloCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRemoverVacinaModeloCadastrarMouseClicked
        int linha = tableModelo2.getSelectedRow();
        
        if(linha == -1){
            JOptionPane.showMessageDialog(this,"Selecione uma vacina");
        }
        else{
            int n = linha;
            DefaultTableModel dtm = (DefaultTableModel) tableModelo2.getModel();
            dtm.removeRow(linha);   

            while(n < dtm.getRowCount()){
                dtm.setValueAt(n+1, n, 0);
                n++;
            }
            JOptionPane.showMessageDialog(this,"Vacina removida com sucesso!");
        }
    }//GEN-LAST:event_botaoRemoverVacinaModeloCadastrarMouseClicked

    private void mudarToTela1(){
        clearFields();
        clearTable();
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "tela1");
        
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(false);
        botaoInferiorCadastrarModelo(false);
    }
    
    private void mudarToTela2(){
        clearFields();
        clearTable();
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "tela2");
        
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoCadastrarModelo.setVisible(true);
        botaoInferiorModeloFinal(false);
        botaoInferiorCadastrarModelo(false);
    }
    
    private void mudarToTela3(){
        clearFields();
        clearTable();
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "tela3");
        
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(true);
        botaoInferiorCadastrarModelo(false);
    }
    
    private void mudarToTela4(){
        clearFields();
        clearTable();
        
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "tela4");
        
        botaoInferiorCarteira(false);
        botaoInferiorModeloInicial(false);
        botaoInferiorModeloFinal(false);
        botaoInferiorCadastrarModelo(true);
        
    }
    
 
    private void clearFields(){
        // Primeira tela
        textCpfCarteira.setText("");
        textNomeCarteira.setText("");
        labelC.setText("");
        labelN.setText("");
                
        // Segunda tela
        textEspecieModelo.setText("");
        textRacaModelo.setText("");
        
        // Terceira tela
        labelRaca.setText("");
        labelEspecie.setText("");
        
        // Quarta tela
        textEspecieModeloCadastrar.setText("");
        textRacaModeloCadastrar.setText("");
        
    }
    
    private void clearTable(){
        DefaultTableModel dtm = (DefaultTableModel) tableVacina.getModel();
        while(dtm.getRowCount() != 0){
            dtm.removeRow(0);   
        }
        
        dtm = (DefaultTableModel) tableModelo1.getModel();
        while(dtm.getRowCount() != 0){
            dtm.removeRow(0);   
        }
        
        dtm = (DefaultTableModel) tableModelo2.getModel();
        while(dtm.getRowCount() != 0){
            dtm.removeRow(0);   
        }
        
        dtm = (DefaultTableModel) tableModelo3.getModel();
        while(dtm.getRowCount() != 0){
            dtm.removeRow(0);   
        }
        
    }
    
    private void botaoInferiorCarteira(boolean a){
        botaoRemoverVacinaCarteira.setVisible(a);
        botaoAgendarVacinaCarteira.setVisible(a);
        botaoAplicarVacinaCarteira.setVisible(a);
        botaoInserirVacinaCarteira.setVisible(a);
    }
    
    private void botaoInferiorModeloInicial(boolean a){
        botaoExcluirModelo.setVisible(a);
        botaoAlterarModelo.setVisible(a);
        
    }
    
    private void botaoInferiorModeloFinal(boolean a){
        botaoRemoverVacinaModelo.setVisible(a);
        botaoInserirVacinaModelo.setVisible(a);
    }
        
    private void botaoInferiorCadastrarModelo(boolean a){
        botaoRemoverVacinaModeloCadastrar.setVisible(a);
        botaoInserirVacinaModeloCadastrar.setVisible(a);
        botaoCadastrarModeloCadastrar.setVisible(a);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAgendarVacinaCarteira;
    private javax.swing.JButton botaoAlterarModelo;
    private javax.swing.JButton botaoAplicarVacinaCarteira;
    private javax.swing.JButton botaoBuscarCarteira;
    private javax.swing.JButton botaoBuscarModelo;
    private javax.swing.JButton botaoCadastrarModelo;
    private javax.swing.JButton botaoCadastrarModeloCadastrar;
    private javax.swing.JButton botaoExcluirModelo;
    private javax.swing.JButton botaoInserirVacinaCarteira;
    private javax.swing.JButton botaoInserirVacinaModelo;
    private javax.swing.JButton botaoInserirVacinaModeloCadastrar;
    private javax.swing.JButton botaoLimparCarteira;
    private javax.swing.JButton botaoLimparModelo;
    private javax.swing.JButton botaoRemoverVacinaCarteira;
    private javax.swing.JButton botaoRemoverVacinaModelo;
    private javax.swing.JButton botaoRemoverVacinaModeloCadastrar;
    private javax.swing.JMenu carteiraVacinacao;
    private javax.swing.JLabel cpfClienteCarteira;
    private javax.swing.JLabel especiePetModelo;
    private javax.swing.JLabel especiePetModeloCadastrar;
    private javax.swing.JLabel fundoCarteira;
    private javax.swing.JLabel fundoModelo;
    private javax.swing.JLabel fundoModelo1;
    private javax.swing.JLabel fundoModelo2;
    private javax.swing.JMenu imprimir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel labelC;
    private javax.swing.JLabel labelCpf;
    private javax.swing.JLabel labelE;
    private javax.swing.JLabel labelEspecie;
    private javax.swing.JLabel labelN;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelR;
    private javax.swing.JLabel labelRaca;
    private javax.swing.JMenu modeloCarteira;
    private javax.swing.JLabel nomePetCarteira;
    private javax.swing.JPanel painelBorda1;
    private javax.swing.JPanel painelBorda2;
    private javax.swing.JPanel painelBorda3;
    private javax.swing.JPanel painelBorda4;
    private javax.swing.JPanel painelCarteira;
    private javax.swing.JPanel painelModelo;
    private javax.swing.JPanel painelModelo1;
    private javax.swing.JPanel painelModelo2;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JLabel racaPetModelo;
    private javax.swing.JLabel racaPetModeloCadastrar;
    private javax.swing.JMenu sair;
    private javax.swing.JTable tableModelo1;
    private javax.swing.JTable tableModelo2;
    private javax.swing.JTable tableModelo3;
    private javax.swing.JTable tableVacina;
    private javax.swing.JPanel tela1;
    private javax.swing.JPanel tela2;
    private javax.swing.JPanel tela3;
    private javax.swing.JPanel tela4;
    private javax.swing.JTextField textCpfCarteira;
    private javax.swing.JTextField textEspecieModelo;
    private javax.swing.JTextField textEspecieModeloCadastrar;
    private javax.swing.JTextField textNomeCarteira;
    private javax.swing.JTextField textRacaModelo;
    private javax.swing.JTextField textRacaModeloCadastrar;
    // End of variables declaration//GEN-END:variables
}
